from email_ai_detector.features import FEATURE_NAMES, extract_features, iter_segments, split_sentences
from email_ai_detector.features.html_signals import extract_html_features, find_suspicious_comments


def test_feature_vector_is_complete():
    features = extract_features(text="Hello there.", subject="Test", html="<p>Hello there.</p>")
    assert set(FEATURE_NAMES) == set(features.vector)
    assert all(isinstance(value, float) for value in features.vector.values())


def test_template_and_comment_detection():
    html = "<!-- Generated by template --><p>{{name}}</p>"
    features = extract_html_features(html)
    assert features["template_variable"] == 1.0
    assert features["suspicious_comment"] == 1.0
    assert find_suspicious_comments(html)


def test_sentence_offsets_match_source():
    text = "First sentence. Second one!\n\nThird"
    for start, end, sentence in split_sentences(text):
        assert text[start:end] == sentence


def test_segments_cover_sentences():
    text = "One. Two. Three."
    segments = list(iter_segments(text))
    assert len(segments) == 3
    assert segments[0]["features"]["segment_is_first"] == 1.0
    assert segments[-1]["features"]["segment_is_last"] == 1.0


def test_categories_within_unit_range():
    features = extract_features(
        text="Dear Alex, we are pleased to inform you.\n\nClaim now: https://example.org\n\nBest regards, Team",
        subject="Exclusive opportunity",
        html="<p>text</p>",
        ocr_text="CLAIM NOW",
    )
    assert set(features.categories) >= {"subject", "opener", "body", "cta", "closer", "html_template", "image"}
    assert all(0.0 <= value <= 1.0 for value in features.categories.values())
