MARKETING_PHRASES = (
    "exclusive opportunity",
    "limited seats",
    "limited time",
    "do not miss out",
    "act now",
    "exceptional gains",
    "unlock your potential",
    "innovative approach",
    "effective solutions",
    "seamless experience",
    "drive sustainable growth",
    "optimize processes",
    "take advantage",
    "we are excited",
    "we are pleased",
    "rest assured",
    "peace of mind",
    "уникальная возможность",
    "ограниченное предложение",
    "не упустите",
    "успейте",
    "выгодные условия",
    "надёжное решение",
    "надежное решение",
    "индивидуальный подход",
    "рады сообщить",
    "с радостью сообщаем",
    "позаботились о вас",
)

CONNECTIVES = (
    "moreover",
    "furthermore",
    "additionally",
    "in addition",
    "however",
    "therefore",
    "as a result",
    "please note",
    "it is important to",
    "we would like to",
    "кроме того",
    "также напоминаем",
    "напоминаем",
    "таким образом",
    "обращаем ваше внимание",
    "важно отметить",
    "пожалуйста, обратите внимание",
    "просим вас",
)

OPENERS = (
    "dear",
    "hello",
    "hi there",
    "good morning",
    "good afternoon",
    "greetings",
    "we hope this email finds you well",
    "hope you are doing well",
    "уважаемый",
    "уважаемая",
    "здравствуйте",
    "добрый день",
    "доброе утро",
    "добрый вечер",
    "надеемся, у вас всё хорошо",
    "надеемся, у вас все хорошо",
)

CLOSERS = (
    "best regards",
    "kind regards",
    "sincerely",
    "warm regards",
    "to your success",
    "thank you for your attention",
    "we appreciate your attention",
    "looking forward to your response",
    "с уважением",
    "с наилучшими пожеланиями",
    "благодарим за внимание",
    "спасибо за уделённое время",
    "ждём вашего ответа",
    "ждем вашего ответа",
)

CALL_TO_ACTION = (
    "click here",
    "claim now",
    "claim your",
    "confirm your identity",
    "confirm your account",
    "verify your account",
    "restore full access",
    "pay the fee",
    "get started",
    "secure your spot",
    "reserve your seat",
    "activate now",
    "download now",
    "перейдите по ссылке",
    "подтвердите",
    "оплатите",
    "получить доступ",
    "забрать приз",
    "активировать",
    "открыть и оплатить",
    "заберите",
)

URGENCY = (
    "immediately",
    "urgent",
    "right now",
    "within 24 hours",
    "last chance",
    "final notice",
    "expires",
    "closing soon",
    "срочно",
    "немедленно",
    "в течение 24 часов",
    "последний шанс",
    "истекает",
    "просрочено",
)

GENERIC_GREETINGS = (
    "dear customer",
    "dear user",
    "dear client",
    "dear sir or madam",
    "valued customer",
    "уважаемый клиент",
    "уважаемый пользователь",
    "дорогой клиент",
)

TYPO_TOKENS = (
    "youre",
    "acount",
    "adress",
    "recieve",
    "seperate",
    "reciept",
    "occured",
    "неоплачено",
    "пожалуйсто",
    "аккоунт",
)

TEMPLATE_PATTERNS = (
    r"\{\{\s*[\w.\-]+\s*\}\}",
    r"\{%\s*[\w.\-]+\s*%\}",
    r"\[\s*(?:NAME|FIRST_?NAME|EMAIL|COMPANY|DATE|LINK|ИМЯ|ФАМИЛИЯ|КОМПАНИЯ|ССЫЛКА)\s*\]",
    r"%%[A-Z_]+%%",
    r"\$\{[\w.\-]+\}",
)

SUSPICIOUS_COMMENT_MARKERS = (
    "generated",
    "template",
    "placeholder",
    "insert",
    "todo",
    "sample",
    "lorem",
    "ai",
    "prompt",
    "chatgpt",
    "as an ai",
)

FUNCTION_WORDS = (
    "the", "a", "an", "and", "or", "but", "if", "of", "to", "in", "on", "for", "with", "from",
    "by", "at", "as", "that", "this", "these", "those", "is", "are", "was", "were", "be", "been",
    "will", "would", "can", "could", "should", "have", "has", "had", "not", "no", "your", "you",
    "we", "our", "it", "its",
    "и", "или", "но", "если", "что", "чтобы", "как", "в", "во", "на", "по", "для", "с", "со",
    "от", "до", "из", "за", "при", "об", "о", "у", "к", "же", "бы", "не", "ни", "это", "этот",
    "вы", "ваш", "ваша", "ваше", "ваши", "мы", "наш", "наша", "они",
)

IMPERATIVE_OPENINGS = (
    "click", "confirm", "verify", "pay", "claim", "restore", "check", "review", "update",
    "download", "activate", "register", "call", "reply", "visit", "order",
    "нажмите", "подтвердите", "оплатите", "проверьте", "обновите", "скачайте", "активируйте",
    "перейдите", "заберите", "откройте", "свяжитесь", "ответьте", "закажите",
)
